### ISSUE TITLE
Add webpack@4 support.

### ISSUE THREAD

**Issue by sanex3339** [jrparish/tslint-webpack-plugin#10]
Webpack@4 just released, so it will nice to have it support (it backward compatible but it's nice to support new API).

https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

* plugin method is backward-compatible
* plugins should use Compiler.hooks.xxx.tap(<plugin name>, fn) now

Other breaking changes related to plugins:
https://github.com/webpack/webpack/releases/tag/v4.0.0

**Comment by jrparish** [comment]
Published v1.2.0 with support for webpack 4. Let me know if there are any issues.
