### ISSUE TITLE
files[] should be optional if project is specified

### ISSUE THREAD

**Issue by sliekens** [jrparish/tslint-webpack-plugin#24]
TSLint CLI allows you to specify the path to a tsconfig file and it will use that to determine the includes/excludes.

```sh
tslint --project ./tsconfig.json
```

I couldn't find how to replicate this behavior with `tslint-webpack-plugin`. I get a warning no matter what I do.

> [tslint-plugin] No `files` option specified.

**Comment by jrparish** [comment]
Currently it requires files to be specified, this would be a good enhancement though.
