### ISSUE TITLE
Support for rules which require type information?

### ISSUE THREAD

**Issue by pelotom** [jrparish/tslint-webpack-plugin#3]
If I try to use a rule that requires type information, I get for example

```
Warning: The 'no-unused-variable' rule requires type information.
```

Is there a way to point this plugin to the `tsconfig.json` so that it can use the TypeScript compiler?

**Comment by jrparish** [comment]
Thanks for the request, I'll look into this!

**Comment by pelotom** [comment]
Never mind, I missed the part in the `README` where it says you can pass through [the standard options](https://github.com/palantir/tslint/blob/master/src/runner.ts). Works fine if I set the `typeCheck` and `project` options correctly.
