### ISSUE TITLE
Start linting at the same time as compilation

### ISSUE THREAD

**Issue by pelotom** [jrparish/tslint-webpack-plugin#4]
It looks like linting starts only once the regular webpack compilation has finished. Is this intentional? Would it be possible to at least have an option to do the linting in parallel with the rest of the compilation?

**Comment by jrparish** [comment]
It was intentional to keep the output separate. We could probably add the option to start immediately.

**Comment by pelotom** [comment]
Would definitely be interested in that feature 👍

**Comment by SebastianStehle** [comment]
Hi, I created a PR for that: https://github.com/jrparish/tslint-webpack-plugin/pull/16

**Comment by jrparish** [comment]
Added in #16
