### ISSUE TITLE
Lint errors should fail the webpack build

### ISSUE THREAD

**Issue by pelotom** [jrparish/tslint-webpack-plugin#5]
My expectation is that lint warnings should not fail the webpack build but lint errors should; this is the behavior of [`tslint-loader`](https://github.com/wbuchwalter/tslint-loader), [`fork-ts-checker-webpack-plugin`](https://github.com/Realytics/fork-ts-checker-webpack-plugin) and [`ts-checker-webpack-plugin`](https://github.com/zinserjan/ts-checker-webpack-plugin).

**Comment by hupfaufnet** [comment]
This would be a very good behavior for me too.

**Comment by vreality64** [comment]
I agree.

I think [this link](https://github.com/wbuchwalter/tslint-loader/blob/c2f69d21c1ba7da4f02bc927ce185ca816dda41d/index.js#L69-L74) will help solve the problem.

**Comment by mischkl** [comment]
+1

**Comment by mischkl** [comment]
This is mandatory behavior for us. We are replacing Grunt with Webpack and previously our CI build failed if there were linting issues. With this plugin it is not possible for us to integrate lint-checking into our CI! :(

**Comment by cajoy** [comment]
Any progress on it?

**Comment by SebastianStehle** [comment]
My PR also fixes this issue: https://github.com/jrparish/tslint-webpack-plugin/pull/16

**Comment by jrparish** [comment]
Added in #16
