### ISSUE TITLE
better support for exclude options

### ISSUE THREAD

**Issue by vreality64** [jrparish/tslint-webpack-plugin#9]
`tslint` has two required option
1. files
2. exclude 

However, **there is no description for the exclude option** in README.

So it is a good idea to let them know that this is a required option, or to set a default. I personally prefer to set the default value to `[]`. When the option is missing, the following error appears. But it is not so clear.

> Error starting linter: TypeError: Cannot read property 'map' of undefined

**Comment by jrparish** [comment]
I believe this `exclude` option was made required in the latest version of TSLint. 
I like the idea of defaulting to `[]` to keep the plugin's configuration simple.

**Comment by jrparish** [comment]
Fixed by 34bb7ddfa981334d256c19b16e43b8ee3c85e4a6 
Published as `v1.1.1`
